### PR TITLE
implemented compare of rrsets function in join_add_cds

### PR DESCRIPTION
**Pull request by romu42**

### CODE REVIEW

**Review by johanix — COMMENTED** [review]
- There's something fishy with the module paths. I see imports of ...music/music/tools/compare, but the new stuff is located in DNSSEC-provisioning/music/tools/compare. Can that really work?
- Ok, I get that you want to keep stuff clean and not put this utility among our various other utilities. So creating a tools/ module is fine. But a .../tools/compare module? Do you really want a separate package for every single utility function? I'm... skeptical :-)

**Review by johanix — COMMENTED** [review]
Där du sedan använder den nya funktionen (som ser exakt rätt ut) så ser jag:

`if !match {
 				matches = false`

och sedan så triggar du på !matches lite längre ut och sätter då en StopReason. Men varför mixtra med !match --> matches? Flytta antingen in din StopReason eller deklarera match lite längre ut så borde du slippa trasslet.

**Comment by romu42** [comment]
- module paths: yes!  I totally missed the extra '/music' in the path. I will see how I can fix this.
- /tools vs /tools/compare, I am not strongly opinionated here. I just wanted it to have its own fairly self-explained place. We can check with someone more knowing about it and get a recommendation.
- the if '!match ....'  etc is for logging, I am not sure it will survive future revisions, but it is so that we get decent logging and stop reason if it doesn't work. I have unformulated thoughts about logging vs stop reasons.

**Comment by johanix** [comment]
Ack. Vi pratar mer om det nästa vecka. Jag tror fortfarande att det måste gå att förenkla det med !match ==> matches.

Apropos så kom jag på hur man kan konvertera tillbaka en dns.FOO till en dns.RR. Så här gör man:

Antag att mySOA är en *dns.SOA och du vill få RR att vara samma data men typen dns.RR. Då räcker det med:

RR := dns.RR(&mySOA)

Trevlig helg!

**Comment by EricIO** [comment]
In the /tools /tools/compare discussion I think I agree with @johanix and say that it would be better to place it in the `/tools` module in its own file called `compare.go`. That way it will have its own place but there is no need to make longer and longer path names (and if I'm going to be super nitpicky I might even rename the tools module to utils).

**Comment by romu42** [comment]
ok, that works for me, regards to the name of the module I based it on this: 
https://github.com/golang-standards/project-layout
That is why I chose ```/tools```

**Comment by romu42** [comment]
comparerrset.go renamed to rrset.go and moved to music/.

I also cleaned up a lot of errors with print/log statements.

**Review by johanix — APPROVED** [review]
Looking good!

**Pull request merged**
