### PR TITLE
cleaning up personal test scripts

### PR DESCRIPTION
**Pull request by romu42**

### CODE REVIEW

**Review by johanix — COMMENTED** [review]
So, while I agree that musical.tsig doesn't belong in the root directory, nor that the meat_test.sh file belongs in the music-cli directory, I do not agree that the right fix is to just delete them.

On the contrary, would suggest that a new directory, "examples" would be a suitable location for a possibly growing collection of name server configs, zones, keys, scripts, etc, that can be of help for future testers of MUSIC.

**Comment by johanix** [comment]
"meat_test.sh"? 

Damn you, autocorrect!

**Comment by romu42** [comment]
As the PR says and the issue says, this is all my personal test stuff. Which was incorrectly in the repository.  It should be deleted from the repository. If we need an examples and some setup stuff then we should add an issue for that and then implement it. One is not dependent on the the other.

**Comment by johanix** [comment]
Well your musiclab.tsig key is already exposed forever, so we can just as well use that as the example :-)

**Review by johanix — APPROVED** [review]

**Comment by romu42** [comment]
> Well your musiclab.tsig key is already exposed forever, so we can just as well use that as the example :-)

I know, that is why it is changed and I am cleaning up.

**Pull request merged**
